name: "Go Test"

on:
  workflow_call:
  workflow_dispatch: {}

jobs:
  test:
    name: Go Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
          # - os: ubuntu-latest
          #   goos: linux
          #   goarch: arm64
          # - os: macos-latest
          #   goos: darwin
          #   goarch: amd64
          # - os: macos-latest
          #   goos: darwin
          #   goarch: arm64
          # - os: windows-latest
          #   goos: windows
          #   goarch: amd64
    steps:
      - uses: actions/checkout@v4

      - name: Install linux dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libgtk-3-dev libwebkit2gtk-4.1-dev build-essential pkg-config xvfb x11-xserver-utils at-spi2-core xdg-desktop-portal-gtk
          version: 1.0

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/.cache/go-build
          key: go-${{ hashFiles('**/go.sum') }}

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
        
      - name: Ensure Dist
        run: |
          mkdir -p ./frontend/dist
          echo "<html>Fake</html>" > ./frontend/dist/index.html

      - name: generate test coverage
        run: go test ./... -coverprofile=./cover.out -covermode=atomic

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: cover.out

      - name: Run tests with race detector
        run: go test -race ./...