name: "Linter"

on:
  workflow_call:
  workflow_dispatch: {}

permissions:
  contents: read
  pull-requests: read  # Required for only-new-issues option

jobs:
  go-lint:
    name: Go Lint
    uses: ./.github/workflows/go-lint.yml

  web-lint:
    name: Web Lint
    uses: ./.github/workflows/web-lint.yml
