name: "Tester"

on:
  workflow_call:
  workflow_dispatch: {}

jobs:
  go-test:
    name: Go Test
    uses: ./.github/workflows/go-test.yml

  web-test:
    name: Web Test
    uses: ./.github/workflows/web-test.yml