name: "Go Lint"

on:
  workflow_call:
  workflow_dispatch: {}

permissions:
  contents: read
  pull-requests: read  # Required for only-new-issues option

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install linux dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libgtk-3-dev libwebkit2gtk-4.1-dev build-essential pkg-config xvfb x11-xserver-utils at-spi2-core xdg-desktop-portal-gtk
          version: 1.0

        
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25"  # Match your go.mod version
          cache: true
      
      - name: Ensure Dist
        run: |
          mkdir -p ./frontend/dist
          echo "<html>Fake</html>" > ./frontend/dist/index.html
          
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.8.0
          # Only show new issues on PRs
          only-new-issues: ${{ github.event_name == 'pull_request' }}
          # Optional: working-directory, args, skip-cache, etc
          args: --timeout=5m --config=.golangci.yml
